EECE430_Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^$', views.homepage, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('cars.urls'), name='car'),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^buy/', include('buy.urls'), name='buy'),
    url(r'^testdrive/', include('testdrive.urls'), name='testdrive'),
    url(r'^account/$', views.account_redirect, name='account-redirect'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [

    # /accounts/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /accounts/login
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),

    # /accounts/logout
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # /accounts/profile/
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile, name='profile'),

    # /accounts/profile/username/edit
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/edit$', views.addphoto, name='addphoto'),

]

buy/urls.py
from django.conf.urls import url
from . import views

app_name = 'buy'

urlpatterns = [

    # /cars/buy/pk
    url(r'^(?P<pk>[0-9]+)$', views.home, name='home'),
]

testdrive/urls.py
from django.conf.urls import url
from . import views

app_name = 'testdrive'

urlpatterns = [
    # testdrive/booking/pk
    url(r'^booking/(?P<pk>[0-9]+)$', views.createTD, name='booking'),

    # testdrive/pk
    url(r'^details/(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),

    # /testdrive/pk/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$', views.TDDelete.as_view(), name='delete'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class ProfilePhoto(models.Model):
    userImg= models.ImageField(upload_to='media', default='media/default-img.png')
    userPhoto = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return 'Photo of ' + self.userPhoto.username

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import ProfilePhoto


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']
        labels ={
            'username': 'Username',
            'password': 'Password'
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username',
                                                     'id': 'username'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Password',
                                                     'id': 'password'})


class PhotoForm(forms.ModelForm):

    class Meta:
        model = ProfilePhoto
        exclude = ['userPhoto']
        labels = {'userImg': 'Photo'}

    def __int__(self, *args, **kwargs):
        super(PhotoForm, self).__init__(*args, **kwargs)
        self.fields['userImg'].widget.attrs.update({'class': 'custom-file-input', 'id': 'inputGroupFile01'})

accounts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View

from testdrive.models import TDModel
from .forms import UserForm, PhotoForm
from buy.models import BuyModel
from .models import ProfilePhoto


def get_user_profile(request, username):
    user = User.objects.get(username=username)
    template_dict = {}
    hasPhoto = False
    try:
        profilephoto = ProfilePhoto.objects.get(userPhoto=user)
        hasPhoto = True
        photo = profilephoto.userImg
        template_dict.update({'photo': photo, 'hasPhoto': hasPhoto})
    except ObjectDoesNotExist:
        hasPhoto = False
    upcoming = []
    boughtCars = []
    testdrive = TDModel.objects.filter(driver=user)
    bought = BuyModel.objects.filter(buyer=user)
    for drive in testdrive:
        if drive.driveDate> timezone.now():
            upcoming.append(drive)
    for car in bought:
        boughtCars.append(car)
    template_dict.update({"user": user, 'upcoming': upcoming, 'boughtCars': boughtCars})
    return render(request, 'accounts/user_profile.html', template_dict)


class UserFormView(View):
    user = User
    form_class = UserForm
    template_name = 'accounts/RegistrationForm.html'

    # Display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)
        isnotReg = False
        if form.is_valid():
            user = form.save(commit=False)

            # Cleaned normalised data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.email = request.POST['email']
            user.set_password(password)
            user.save()

            # returns user objects if credentials are correct
            user = authenticate(username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('accounts:profile', username)

        isnotReg = True
        return render(request, self.template_name, {'form': form, 'isnotReg': isnotReg})


def addphoto(request, username):
    user = User.objects.get(username=username)
    form = PhotoForm()
    if request.method=='POST':
        photo = request.POST['userImg']
        try:
            p = ProfilePhoto.objects.get(userPhoto=user)
            p.userImg = photo
            p.save()

        except ObjectDoesNotExist:
            ProfilePhoto.objects.create(userImg=photo, userPhoto=user)
        return redirect('accounts:profile', username)
    return render(request, 'accounts/edit_pic.html', {'form': form})

templates/accounts/RegistrationForm.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Sign up</title>
     <link rel="icon" href="{% static 'img/Car_Logo.png' %}">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin-2.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" action="" method="POST">
      {% csrf_token %}
      <img class="mb-4" src="{% static 'img/Car_Logo.png' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal" style="color:white;"> Please sign up</h1>
         {% if isnotReg %}
             <div class="alert alert-danger" role="alert">
                 This username is already taken
             </div>
        {% endif %}
      {% include 'cars/formtemplate.html' %}

         <div class="col-auto">
             <div class="input-group mb-3">
                 <div class="input-group-prepend">
                     <span class="input-group-text" id="basic-addon1">First Name</span>
                 </div>
                 <input type="text" class="form-control" id="exampleInputName1" placeholder="First Name" name="first_name">
             </div>
         </div>
        <div class="col-auto">
             <div class="input-group mb-3">
                 <div class="input-group-prepend">
                     <span class="input-group-text" id="basic-addon1">Last Name</span>
                 </div>
            <input type="text" class="form-control" id="exampleInputName1" placeholder="Last Name" name="last_name">
             </div>
        </div>
        <div class="col-auto">
             <div class="input-group mb-3">
                 <div class="input-group-prepend">
                     <span class="input-group-text" id="basic-addon1">Email</span>
                 </div>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email Address" name="email">
             </div>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        <a class="btn btn-block btn-secondary" href="{% url 'home' %}" role="button">Back to Home</a>
    </form>
  </body>

templates/accounts/edit_pic.html
{% extends 'exterior.html' %}
{% load static %}
{% block title %}Photo Form{% endblock %}

{% block content %}
    <body>
    <div class="jumbotron">
        <h1 class="display-5">Edit Photo</h1>
        <hr class="my-4">
      <form action="" method="post">
          {% csrf_token %}
          <div>
              <div class="panel-body">
                  <h1 class="h3 mb-3 font-weight-normal">Please upload a picture</h1>
                  <div class="form-row align-items-center">
                      {% include 'accounts/formtemplate.html' %}
                  </div>
              </div>
          </div>
          <button class="btn btn-primary" type="submit">Submit</button>
          <a class="btn btn-secondary" href="{% url 'accounts:profile' user.username %}" role="button">Back to Profile</a>
      </form>
    </div>
    </body>
{% endblock %}

templates/accounts/formtemplate.html
{% for field in form %}
    <div class="col-auto">
        <div class="input-group mb-2">
            {{ field }}
        </div>
    </div>
{% endfor %}

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <link rel="icon" href="{% static 'img/Car_Logo.png' %}">
    <title>Sign in</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post">
        {% csrf_token %}
      <img class="mb-4" src="{% static 'img/Car_Logo.png' %}" alt="" width="72" height="72">
      <h1 class="h3 mb-3 font-weight-normal" style="color:white;"> Please sign in</h1>
      <label for="username" class="sr-only">Email address</label>
      <input name="username" type="text" id="username" class="form-control" placeholder="Username" required autofocus>
      <label for="password" class="sr-only">Password</label>
      <input name="password" type="password" id="password" class="form-control" placeholder="Password" required>
      <button name="submit" class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="btn btn-block btn-secondary" href="{% url 'home' %}" role="button">Back to Home</a>
    </form>

  </body>
</html>

templates/accounts/user_profile.html
{% extends   'exterior.html' %}
{% load staticfiles %}
{% block title %}{{ user }}{% endblock %}
{% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a  name="logout" class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}
{% block content %}


    <!-- Jumbotron-->
    <div class="jumbotron jumbotron-fluid">
  <div class="container">

    <h1 class="display-4">
        {% if hasPhoto %}
            <img src="{{ photo.url }}" style="width: 300px; height: 300px;">
        {% else %}
        <img src="{% static 'img/default-img.png' %}" style="width: 300px;" alt="{{user.username}}">
        {% endif %}
        Welcome, {{ user.first_name }}!
    </h1>
       <a href="{% url 'accounts:addphoto' user.username %}" class="badge badge-secondary">Edit Picture</a>
  </div>
    <hr class="my-4">
        <p class="lead">
            <!-- Table -->
        <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Account Details</th>
            <th scope="col">Value</th>

    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">First Name</th>
      <td>{{user.first_name}}</td>
    </tr>
    <tr>
      <th scope="row">Last Name</th>
      <td>{{user.last_name}}</td>
    </tr>
    <tr>
      <th scope="row">Email</th>
      <td>{{user.email}}</td>
    </tr>
  <tr>
      <th scope="row">Username</th>
      <td>{{user.username}}</td>
    </tr>
  <tr>
      <th scope="row">Test Drives Booked</th>
  <td>

  {% if upcoming %}
       <ul>
      {% for drive in upcoming %}
          <li>{{ drive.driveCar }} reserved on {{drive.driveDate}} <a class="badge badge-danger" href="{% url 'testdrive:delete' drive.pk %}">Cancel</a></li>

      {% endfor %}
      </ul>
      {% else %}
      No upcoming testdrives
  {% endif %}

  </td>
    </tr>
   <tr>
      <thp scope="row">Cars Bought</thp>
  <td>

  {% if boughtCars %}
       <ul>
      {% for car in boughtCars %}
          <li> {{ car.boughtCar }}</li>

      {% endfor %}
      </ul>
      {% else %}
      No bought cars
  {% endif %}

  </td>
    </tr>
  </tbody>
</table>
</div>

{% endblock %}