EECE430_Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^$', views.homepage, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('cars.urls'), name='car'),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^buy/', include('buy.urls'), name='buy'),
    url(r'^testdrive/', include('testdrive.urls'), name='testdrive'),
    url(r'^account/$', views.account_redirect, name='account-redirect'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [

    # /accounts/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /accounts/login
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),

    # /accounts/logout
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # /accounts/profile/
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile, name='profile'),

    # /accounts/profile/username/edit
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/edit$', views.addphoto, name='addphoto'),

]

buy/urls.py
from django.conf.urls import url
from . import views

app_name = 'buy'

urlpatterns = [

    # /cars/buy/pk
    url(r'^(?P<pk>[0-9]+)$', views.home, name='home'),
]

cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'

urlpatterns = [
    # /Default landing page
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /cars/index/
    url(r'^index$', views.IndexView.as_view(), name='index'),

    # /cars/pk/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),  name='detail'),

    # /cars/model/add
    url(r'^model/add/$', views.CarCreate, name='cars-add'),

    # /cars/model/pk/
    url(r'^model/(?P<pk>[0-9]+)/$', views.CarUpdate.as_view(), name='cars-update'),

    # /cars/model/pk/delete/
    url(r'^model/(?P<pk>[0-9]+)/delete/$', views.CarDelete.as_view(), name='cars-delete'),

    # /cars/search
    url(r'^search/$', views.Search.as_view(), name='search'),
]

testdrive/urls.py
from django.conf.urls import url
from . import views

app_name = 'testdrive'

urlpatterns = [
    # testdrive/booking/pk
    url(r'^booking/(?P<pk>[0-9]+)$', views.createTD, name='booking'),

    # testdrive/pk
    url(r'^details/(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),

    # /testdrive/pk/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$', views.TDDelete.as_view(), name='delete'),
]

testdrive/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from cars.models import CarModel
from datetime import datetime


class TDModel(models.Model):
    driveDate = models.DateTimeField('Test Drive Date', default=datetime.now)
    driveCar = models.ForeignKey(CarModel, on_delete=models.CASCADE, default=1)
    driver = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def get_absolute_url(self):
        return reverse('testdrive:detail:', kwargs={'driveDate': self.driveDate})

    def __str__(self):
        return self.driveDate.__str__() + ' for ' + self.driveCar.__str__() \
               + ' scheduled for ' + self.driver.username

testdrive/forms.py
from django import forms
from testdrive.models import TDModel


class TDForm(forms.ModelForm):

    class Meta:
        model = TDModel
        exclude = ['driveDate']

testdrive/views.py
import datetime

from django.urls import reverse_lazy
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render
from django.views import generic
from django.views.generic import DeleteView

from cars.models import CarModel
from .forms import TDForm
from django.contrib.auth.models import User
from .models import TDModel


class TDDelete(DeleteView):
    model = TDModel
    user = User
    success_url = reverse_lazy('cars:index')


class DetailView(generic.DetailView):
    template_name = 'testdrive/detail.html'
    model = TDModel
    context_object_name = 'testdrive'


def createTD(request, pk):
    upcoming = []
    testCar = CarModel.objects.get(pk=pk)
    carTestDrives = TDModel.objects.filter(driveCar=testCar)
    for drive in carTestDrives:
        if drive.driveDate > timezone.now():
            upcoming.append(drive)
    if request.method == 'POST':
        user = User.objects.get(username=request.user)
        car = CarModel.objects.get(id=pk)
        drive = request.POST['driveDate']
        if datetime.datetime.strptime(drive, '%Y-%m-%dT%H:%M') >= datetime.datetime.now() + datetime.timedelta(days=3):
            if 8 < datetime.datetime.strptime(drive, '%Y-%m-%dT%H:%M').hour < 17 \
                    and 0 < datetime.datetime.strptime(drive, '%Y-%m-%dT%H:%M').weekday() < 4:
                try:
                    TDModel.objects.get(driveCar=car, driveDate=drive)
                    return render(request, 'testdrive/fail.html', {'pk': pk})
                except ObjectDoesNotExist:
                        TDModel.objects.create(driveDate=drive, driveCar=car, driver=user)
                        return render(request, 'testdrive/success.html', {'pk': pk})
            else:
                return render(request, 'testdrive/closed.html', {'pk': pk})
        else:
            return render(request, 'testdrive/pastTime.html', {'pk': pk})
    else:
        form = TDForm()
    return render(request, 'testdrive/createTD.html', {'form': form, 'pk': pk, 'upcoming': upcoming})

templates/testdrive/TDModel_confirm_delete.html
{% extends   'exterior.html' %}
{% load staticfiles %}
{%  block title %} Car Remove {%  endblock %}

{% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}


{% block content %}
    <div class="alert alert-danger" role="alert">
  Are you sure you want to cancel?
</div>
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-danger">Cancel</button>
                            <a class="btn btn-outline-secondary" href="{% url 'accounts:profile' user.username %}" role="button">Back to Profile</a>
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </div>


{% endblock %}

templates/testdrive/closed.html
{% extends 'exterior.html' %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Sorry, we are closed</h1>
            <p class="lead">We operate weekdays from 8:00 to 17:00 and you are welcome to choose any time and day in between</p>
            <a class="btn btn-primary" href="{% url 'testdrive:booking' pk %}" role="button">Back</a>
        </div>
    </div>
{% endblock %}

templates/testdrive/createTD.html
{% extends 'exterior.html' %}
{% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}

{% block content %}
    <div class="jumbotron">
    <h1 class="display-4">Please specify date and time</h1>
        <p class="lead my-1">Bookings should be made 3 days ahead of requested date</p>
        <hr class="my-4">
<form method="post">
    {% csrf_token %}
    <div class="col-sm-5">
    <div class="input-group mb-3">

        <input type="datetime-local"  class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" name="driveDate">
    </div>
    <div>
        <button type="submit" class="btn btn-success">Submit</button>
        <a class="btn btn-secondary" href="{% url 'cars:detail' pk=pk %}" role="button">Back to Details</a>
    </div>
        </div>
</form>
    {% if upcoming %}
  <p><table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Reserved dates for this car</th>
      <th scope="col">Booked by</th>
    </tr>
  </thead>
  <tbody>
   {% for drive in upcoming %}
       <tr>
           <td>{{ drive.driveDate }}</td>
           <td>{{ drive.driver }}</td>
       </tr>
      {% endfor %}
  </tbody>
</table>
    {% endif %}
    </div>
{% endblock %}

templates/testdrive/detail.html
{% extends 'exterior.html' %}
{% block content %}

    <h3>{{ testdrive}}</h3>

{%  endblock %}

templates/testdrive/fail.html
{% extends 'exterior.html' %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Sorry, someone was faster than you</h1>
            <p class="lead">Someone has booked this car on this date, unlucky. Book another date and take revenge!</p>
            <a class="btn btn-primary" href="{% url 'testdrive:booking' pk %}" role="button">Back</a>
        </div>
    </div>
{% endblock %}

templates/testdrive/pastTime.html
{% extends 'exterior.html' %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">Please pick a valid date</h1>
            <p class="lead">To be able to book your test drive, you must reserve before at least 3 days</p>
            <a class="btn btn-primary" href="{% url 'testdrive:booking' pk %}" role="button">Back</a>
        </div>
    </div>
{% endblock %}

templates/testdrive/success.html
{% extends 'exterior.html' %}
{% block content %}
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">You are all set!</h1>
            <p class="lead">Your test drive has been scheduled! See you soon!</p>
            <a class="btn btn-primary" href="{% url 'cars:detail' pk %}" role="button">Back</a>
        </div>
    </div>
{% endblock %}