EECE430_Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    url(r'^$', views.homepage, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^cars/', include('cars.urls'), name='car'),
    url(r'^accounts/', include('accounts.urls'), name='accounts'),
    url(r'^buy/', include('buy.urls'), name='buy'),
    url(r'^testdrive/', include('testdrive.urls'), name='testdrive'),
    url(r'^account/$', views.account_redirect, name='account-redirect'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [

    # /accounts/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /accounts/login
    url(r'^login/$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),

    # /accounts/logout
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # /accounts/profile/
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile, name='profile'),

    # /accounts/profile/username/edit
    url(r'^profile/(?P<username>[a-zA-Z0-9]+)/edit$', views.addphoto, name='addphoto'),

]

buy/urls.py
from django.conf.urls import url
from . import views

app_name = 'buy'

urlpatterns = [

    # /cars/buy/pk
    url(r'^(?P<pk>[0-9]+)$', views.home, name='home'),
]

cars/urls.py
from django.conf.urls import url
from . import views

app_name = 'cars'

urlpatterns = [
    # /Default landing page
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /cars/index/
    url(r'^index$', views.IndexView.as_view(), name='index'),

    # /cars/pk/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(),  name='detail'),

    # /cars/model/add
    url(r'^model/add/$', views.CarCreate, name='cars-add'),

    # /cars/model/pk/
    url(r'^model/(?P<pk>[0-9]+)/$', views.CarUpdate.as_view(), name='cars-update'),

    # /cars/model/pk/delete/
    url(r'^model/(?P<pk>[0-9]+)/delete/$', views.CarDelete.as_view(), name='cars-delete'),

    # /cars/search
    url(r'^search/$', views.Search.as_view(), name='search'),
]

testdrive/urls.py
from django.conf.urls import url
from . import views

app_name = 'testdrive'

urlpatterns = [
    # testdrive/booking/pk
    url(r'^booking/(?P<pk>[0-9]+)$', views.createTD, name='booking'),

    # testdrive/pk
    url(r'^details/(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),

    # /testdrive/pk/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$', views.TDDelete.as_view(), name='delete'),
]

cars/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime


class CarModel(models.Model):
    CarImg = models.ImageField(upload_to='media', default='media/default.jpg')
    CarBrand = models.CharField(max_length=5000)
    Model = models.CharField(max_length=5000)
    Year = models.DateField('Year of Manufacture', default=datetime.now)
    Engine = models.FloatField(default=1.0)
    Cylinders = models.CharField(max_length=5000)
    DoorsNum = models.IntegerField(default=4)
    Weight = models.IntegerField(default=1000)
    Fuel = models.CharField(max_length=5000)
    BodyType = models.CharField(max_length=5000)
    Transmission = models.CharField(max_length=5000)
    HP = models.IntegerField(default=100)
    TopSpeed = models.IntegerField(default=220)
    FuelCapacity = models.IntegerField(default=50)
    Country = models.CharField(max_length=5000)
    Mileage = models.IntegerField(default=0)
    Color = models.CharField(max_length=5000)

    def get_absolute_url(self):
        return reverse('cars:detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.CarBrand + ' - ' + self.Model + ' ' + str(self.Year.year)

cars/forms.py
from django.contrib.auth.models import User
from django import forms
from django.forms import TextInput

from cars.models import CarModel


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class CarModelForm(forms.ModelForm):
    class Meta:
        model = CarModel
        fields = '__all__'
        labels = {
            'CarBrand': 'Brand Name',
            'Model': 'Model Name',
            'DoorsNum': 'Number of Doors',
            'BodyType': 'Body Type',
            'HP': 'Horsepower',
            'TopSpeed': 'Top Speed',
            'FuelCapacity': 'Fuel Capacity',
            'Fuel': 'Fuel Type',
            'Engine': 'Engine Size'
        }

    def __init__(self, *args, **kwargs):
        super(CarModelForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control'})

cars/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic.edit import UpdateView, DeleteView
from .models import CarModel
from django.urls import reverse_lazy
from django.views import View
from django.views import generic
from .forms import CarModelForm
from buy.models import BuyModel
import datetime


class IndexView(generic.ListView):
    template_name = 'cars/index.html'
    context_object_name = 'carList'
    user = User

    def get_queryset(self):
        return CarModel.objects.all()


class DetailView(generic.DetailView):
    context_object_name = 'car'
    model = CarModel
    template_name = 'cars/detail.html'
    user = User
    buyer = BuyModel


def CarCreate(request):
    user = User.objects.get(username=request.user)
    form = CarModelForm
    if request.method == 'POST':
        carspecs = ['CarBrand',
                    'Model',
                    'Year',
                    'Engine',
                    'GearNum',
                    'TransmissionType',
                    'DoorsNum',
                    'Weight',
                    'Fuel',
                    'BodyType',
                    'CylindersNum',
                    'CylindersType',
                    'HP',
                    'TopSpeed',
                    'FuelCapacity',
                    'Country',
                    'Mileage',
                    'Color']

        form_data = []
        for l in carspecs:
            form_data.append(request.POST.get(l))

        carBrand = form_data.__getitem__(0).capitalize()
        model = form_data.__getitem__(1).capitalize()
        year=datetime.datetime.strptime(form_data.__getitem__(2), '%Y-%m').year.__str__() + '-01-01'
        engine = form_data.__getitem__(3)
        transmission = form_data.__getitem__(4) + ' SP '+ form_data.__getitem__(5)
        doorsNum = form_data.__getitem__(6)
        weight = form_data.__getitem__(7)
        fuelType = form_data.__getitem__(8)
        bodyType = form_data.__getitem__(9)
        cylinders = form_data.__getitem__(11) + ' ' + form_data.__getitem__(10)
        hp = form_data.__getitem__(12)
        topSpeed = form_data.__getitem__(13)
        fuelCap = form_data.__getitem__(14)
        country = form_data.__getitem__(15)
        mileage = form_data.__getitem__(16)
        color = form_data.__getitem__(17).capitalize()

        CarModel.objects.create(CarBrand=carBrand,
                                Model=model,
                                Year=year,
                                Engine=engine,
                                Transmission=transmission,
                                DoorsNum=doorsNum,
                                Weight=weight,
                                Fuel=fuelType,
                                BodyType=bodyType,
                                Cylinders=cylinders,
                                HP=hp,
                                TopSpeed=topSpeed,
                                FuelCapacity=fuelCap,
                                Country=country,
                                Mileage=mileage,
                                Color=color)
        return redirect('cars:index')

    return render(request, 'cars/CarModel_add.html', {'user': user, 'form':form})


class CarUpdate(UpdateView):
    model = CarModel
    form_class = CarModelForm
    user = User


class CarDelete(DeleteView):
    model = CarModel
    success_url = reverse_lazy('cars:index')
    user = User


class Search(View):
    form_class = CarModelForm
    user = User
    template_name = 'cars/SearchForm.html'

    def get(self, request):
        carspecs = ['CarBrand', 'Model', 'Year', 'Engine', 'Cylinders', 'DoorsNum',
                    'Weight', 'Fuel', 'BodyType', 'Transmission', 'HP', 'TopSpeed',
                    'FuelCapacity', 'Country', 'Mileage', 'Color']

        searchedItem = CarModel.objects.all()
        carList = CarModel.objects.all()
        form = self.form_class(request.GET)

        ordered = []
        for i in carspecs:
            ordered.append(CarModel.objects.values(i).distinct().order_by(i).all())

        form_data = []
        for l in carspecs:
            form_data.append(request.GET.get(l))

        if not form_data[0] == "All":
            searchedItem = searchedItem.filter(CarBrand=form_data.__getitem__(0))
        if not form_data[1] == "All":
            searchedItem = searchedItem.filter(Model=form_data.__getitem__(1))
        if not form_data[2] == "All" and not form_data[2] is None:
            year = datetime.datetime(datetime.datetime.strptime(form_data.__getitem__(2), '%Y').year, 1, 1)
            searchedItem = searchedItem.filter(Year=year)
        else:
            searchedItem = searchedItem.all()
        if not form_data[3] == "All":
            searchedItem = searchedItem.filter(Engine=form_data.__getitem__(3))
        if not form_data[4] == "All":
            searchedItem = searchedItem.filter(Cylinders=form_data.__getitem__(4))
        if not form_data[5] == "All":
            searchedItem = searchedItem.filter(DoorsNum=form_data.__getitem__(5))
        if not form_data[6] == "All":
            searchedItem = searchedItem.filter(Weight=form_data.__getitem__(6))
        if not form_data[7] == "All":
            searchedItem = searchedItem.filter(Fuel=form_data.__getitem__(7))
        if not form_data[8] == "All":
            searchedItem = searchedItem.filter(BodyType=form_data.__getitem__(8))
        if not form_data[9] == "All":
            searchedItem = searchedItem.filter(Transmission=form_data.__getitem__(9))
        if not form_data[10] == "All":
            searchedItem = searchedItem.filter(HP=form_data.__getitem__(10))
        if not form_data[11] == "All":
            searchedItem = searchedItem.filter(TopSpeed=form_data.__getitem__(11))
        if not form_data[12] == "All":
            searchedItem = searchedItem.filter(FuelCapacity=form_data.__getitem__(12))
        if not form_data[13] == "All":
            searchedItem = searchedItem.filter(Country=form_data.__getitem__(13))
        if not form_data[14] == "All":
            searchedItem = searchedItem.filter(Mileage=form_data.__getitem__(14))
        if not form_data[15] == "All":
            searchedItem = searchedItem.filter(Color=form_data.__getitem__(15))

        template_dict = \
            {
                'form': form,
                'carList': carList,
                'orderedByBrand': ordered[0],
                'orderedByModel': ordered[1],
                'orderedByYear': ordered[2],
                'orderedByEngine': ordered[3],
                'orderedByCylinders': ordered[4],
                'orderedByDoors': ordered[5],
                'orderedByWeight': ordered[6],
                'orderedByFuel': ordered[7],
                'orderedByBody': ordered[8],
                'orderedByTrans': ordered[9],
                'orderedByHP': ordered[10],
                'orderedBySpeed': ordered[11],
                'orderedByCap': ordered[12],
                'orderedByCountry': ordered[13],
                'orderedByMile': ordered[14],
                'orderedByColor': ordered[15],
                'searchedItem': searchedItem
            }
        return render(request, self.template_name, template_dict)

templates/cars/CarModel_add.html
{% extends 'exterior.html' %}
{% load static %}
{% block title %}Car Form{% endblock %}
{% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}
{% block content %}
    <body>
    <div class="jumbotron">
        <h1 class="display-5">Car Form</h1>
        <hr class="my-4">
      <form action="" method="post">
          {% csrf_token %}
          <div>
              <div class="panel-body">
                  <h1 class="h3 mb-3 font-weight-normal"> Please specify the following</h1>
                  <div class="form-row align-items-center">
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Car Brand</div>
                              </div>
                              <input type="text" class="form-control" id="exampleInputName1" title="CarBrand" name="CarBrand" placeholder="Ex: Volkswagen" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Car Model</div>
                              </div>
                              <input type="text" class="form-control" id="inlineFormInputGroup" title="Model" name="Model" placeholder="Ex: Passat" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Year of Manufacture</div>
                              </div>

                              <input type="month" class="form-control" placeholder="Year" aria-label="Year" aria-describedby="basic-addon1" name="Year" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Engine Capacity</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="Model" min="1.0" max="5.0" name="Engine" placeholder="Ex: 1.0" step="0.1" required>
                              <div class="input-group-append">
                                <span class="input-group-text">L</span>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Number of Gears</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" min="3" max="7" title="GearNum" name="GearNum" placeholder="Ex: 4" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Transmission Type</div>
                              </div>
                                <select class="custom-select" id="inputGroupSelect01" title="TransmissionType" name="TransmissionType">
                                    <option selected>MANUAL</option>
                                    <option value="AUTOMATIC">AUTOMATIC</option>
                                    <option value="AUTO DIRECT SHIFT">AUTO DIRECT SHIFT</option>
                                    <option value="AUTO G-TRONIC">AUTO G-TRONIC</option>
                                    <option value="CVT MULTITRONIC">CVT MULTITRONIC</option>
                                    <option value="SEQUENTIAL AUTO">SEQUENTIAL AUTO</option>
                                    <option value="AUTO STEPTRONIC">AUTO STEPTRONIC</option>
                                </select>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Number of Doors</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="DoorsNum" min="2" max="6" name="DoorsNum" placeholder="Ex: 2" step="2" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Weight of Car</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="Weight" min="1000" max="10000" name="Weight" placeholder="Ex: 1000" required>
                              <div class="input-group-append">
                                <span class="input-group-text">KG</span>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Fuel Type</div>
                              </div>
                              <select class="custom-select" id="inputGroupSelect01" title="FuelType" name="Fuel" required>
                                    <option selected>95 Petrol</option>
                                    <option value="98 Petrol">98 Petrol</option>
                                    <option value="Diesel">Diesel</option>
                              </select>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Body Type</div>
                              </div>
                              <select class="custom-select" id="inputGroupSelect01" title="BodyType" name="BodyType" required>
                                  <option selected>Sedan</option>
                                  <option value="Hatchback">Hatchback</option>
                                  <option value="Coupe">Coupe</option>
                                  <option value="SUV">SUV</option>
                                  <option value="Mini-SUV">Mini-SUV</option>
                              </select>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Number of Cylinders</div>
                              </div>
                               <input type="number" class="form-control" id="inlineFormInputGroup" min="4" max="8" title="CylindersNum" name="CylindersNum" placeholder="Ex: 4" required>
                                <select class="custom-select" id="inputGroupSelect01" title="CylindersType" name="CylindersType">
                                    <option selected>INLINE</option>
                                    <option value="AUTOMATIC">TURBO</option>
                                </select>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Horsepower</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="HP" min="66" max="1000" name="HP" placeholder="Ex: 100" required>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Top Speed</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="TopSpeed" min="110" max="429" name="TopSpeed" placeholder="Ex: 220" required>
                              <div class="input-group-append">
                                <span class="input-group-text">KM/H</span>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Fuel Capacity</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="FuelCapacity" min="40" max="100" name="FuelCapacity" placeholder="Ex: 42" required>
                              <div class="input-group-append">
                                <span class="input-group-text">L</span>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Country of Manufacture</div>
                              </div>
                               <select class="custom-select" id="inputGroupSelect01" title="Country" name="Country" required>
                                  {% include 'country_select.html' %}
                              </select>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Mileage</div>
                              </div>
                              <input type="number" class="form-control" id="inlineFormInputGroup" title="Mileage" min="0" max="6000000" name="Mileage" placeholder="Ex: 14300"required>
                              <div class="input-group-append">
                                <span class="input-group-text">KM</span>
                              </div>
                          </div>
                      </div>
                      <div class="col-auto">
                          <div class="input-group mb-2">
                              <div class="input-group-prepend">
                                  <div class="input-group-text">Color</div>
                              </div>
                                 <input type="text" class="form-control" title="Color" name="Color" placeholder="Ex: Red" required>
                          </div>
                      </div>
                  </div>
              </div>
              <button class="btn btn-primary" type="submit">Submit</button>
              <a class="btn btn-secondary" href="{% url 'cars:index' %}" role="button">Back to Index</a>
          </div>
      </form>
    </div>
    </body>
{% endblock %}

templates/cars/detail.html
{% extends   'exterior.html' %}
{% load staticfiles %}
{% block title %} {{ car }}{% endblock %}
{% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}

{% block content %}


    <!-- Jumbotron-->
    <div class="jumbotron">
        <a class="btn btn-outline-dark" href="{% url 'cars:index' %}" role="button">Back</a>
        <h3> </h3>
        <h1 class="display-4">  <img src="{{car.CarImg.url}}" style="width: 300px;" alt="{{car.Model}}"> {{ car}} </h1>
        {% if user.is_authenticated %}
            <a  href="{% url 'testdrive:booking' car.id%}" class="badge badge-secondary">Book a test drive</a>
            <a  href="{% url 'buy:home' car.id%}" class="badge badge-secondary">Buy this car</a>
        {% else %}
            <a  href="" class="badge badge-secondary">Book a test drive </a>
            <a  href="" class="badge badge-secondary">Buy this car</a>
            <span class="badge badge-danger">Please register or login to access these features</span>
        {% endif %}
        <hr class="my-4">
        <p class="lead">
            <!-- Table -->
        <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Specs</th>
            <th scope="col">Value</th>

    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Car Brand</th>
      <td>{{car.CarBrand}}</td>
    </tr>
    <tr>
      <th scope="row">Engine</th>
      <td>{{car.Engine}} L</td>
    </tr>
    <tr>
      <th scope="row">Transmission</th>
      <td>{{car.Transmission}}</td>
    </tr>
  <tr>
      <th scope="row">Year</th>
      <td>{{car.Year.year}}</td>
    </tr>
  <tr>
      <th scope="row">Cylinders</th>
      <td>{{car.Cylinders}}</td>
    </tr>
  <tr>
      <th scope="row">Doors</th>
      <td>{{car.DoorsNum}}</td>
    </tr>
  <tr>
      <th scope="row">Fuel Type</th>
      <td>{{car.Fuel}}</td>
    </tr>
  <tr>
      <th scope="row">Body</th>
      <td>{{car.BodyType}}</td>
    </tr>
  <tr>
      <th scope="row">Horsepower</th>
      <td>{{car.HP}}</td>
    </tr>
  <tr>
      <th scope="row">Country</th>
      <td>{{car.Country}}</td>
    </tr>
  <tr>
      <th scope="row">Mileage</th>
      <td>{{car.Mileage}} km</td>
    </tr>
  <tr>
      <th scope="row">Color</th>
      <td>{{car.Color}}</td>
    </tr>
  <tr>
      <th scope="row">Top Speed</th>
      <td>{{car.TopSpeed}} km\h</td>
    </tr>
  </tbody>
</table>
    </div>

{% endblock %}

templates/cars/formtemplate.html
{% for field in form %}
    <div class="col-auto">
        <label class="sr-only">{{field.label}}</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text">{{ field.label }}</div>
            </div>
            {{ field }}
        </div>
    </div>
{% endfor %}

templates/cars/index.html
{% extends   'exterior.html' %}
{% load staticfiles %}
{% block add %} {% if user.is_authenticated and user.is_staff %}
            <a href="{% url 'cars:cars-add' %}" class="btn btn-primary btn-outline-info">Add Car</a>
    {% endif %} {% endblock %}
{% block title%} Car Index {% endblock %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock %}
    {% block login %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:profile' username=user.username %}" style="color: white; ">Welcome, {{ user.first_name }}</a>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" style="color: white; ">Login</a>
        {% endif %}
    {% endblock %}

    {% block logout %}
        {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" style="color: white; ">Logout</a>
        {% else %}

            <a class="nav-item nav-link" href="{% url 'accounts:register' %}" style="color:white;">Register</a>
        {% endif %}
    {% endblock %}
{% block content %}


  <!-- Car Cards -->
  <ul id="menu">
      {% for car in carList %}
          <li>
              <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{{car.CarImg.url}}" alt="{{car.Model}}">
                  <div class="card-body">
                      <h5 class="card-title">{{car}}</h5>
                      <p class="card-text">{{car.Transmission}} </p>
                      {% if user.is_authenticated and user.is_staff %}
                          <a class="btn btn-primary btn-info" href="{%url 'cars:cars-update' car.id%}" role="button">Edit</a>
                      {% endif %}
                      {% block details %}
                          <a href="{% url 'cars:detail' car.id %}" class="btn btn-primary">Details</a>
                      {% endblock %}
                      {% if user.is_authenticated and user.is_staff %}
                          <a class="btn btn-primary btn-danger" href="{%url 'cars:cars-delete' car.id%}" role="button">Delete</a>
                      {% endif%}
                  </div>
              </div>
          </li>
      {% endfor %}
  </ul>
{% endblock %}